### PR TITLE
Pre-build `forge ffi` within the build script

### PR DESCRIPTION
**Pull request by capossele**
With this addition, running `cargo build` from the root folder results in also building the `forge ffi` cli of the `risc0-ethereum` crate.

Solves #83

### CODE REVIEW

**Comment by nategraf** [comment]
Would it be possible to instead declare the ffi CLI a a dev dependency of `risc0-ethereum-contracts`, or possibly of the template workspace? I think this would be a cleaner way to achieve the same results, unless it doesn't work for some reason.

**Comment by capossele** [comment]
> Would it be possible to instead declare the ffi CLI a a dev dependency of `risc0-ethereum-contracts`, or possibly of the template workspace? I think this would be a cleaner way to achieve the same results, unless it doesn't work for some reason.

Yeah I've tried a couple of different approaches similar to what you have suggested but they were all unsuccessful mainly because cargo does not really like working with two different virtual workspaces

**Comment by nategraf** [comment]
Hmmmm... maybe we can address this issue, and the issue with the location of `Elf.sol` and `ImageID.sol` by adding a Forge remapping as part of `build.rs` to point into the correct folder in the `target` directory, where the source code for both `risc0-ethereum-contracts` and `risc0-forge-ffi` will be cloned. If this works, it could also potentially allow us to drop `risc0-ethereum-contracts` as a submodule. It's a bit speculative, but I think worth trying.

**Comment by capossele** [comment]
Closing for now, I'll reopen once https://github.com/risc0/risc0-ethereum/pull/120 gets merged

**Pull request closed without merging**
